export const COLUMNS = [
  { property: 'healthIndex', label: 'Health Index' },
  { property: 'endDate', label: 'End Date' },
  { property: 'minValueDateTime', label: 'Min Value Date Time' },
  { property: 'type', label: 'Type' },
  { property: 'cowId', label: 'Cow ID' },
  { property: 'animalId', label: 'Animal ID' },
  { property: 'eventId', label: 'Event ID' },
  { property: 'deletable', label: 'Deletable' },
  { property: 'lactationNumber', label: 'Lactation Number' },
  { property: 'daysInLactation', label: 'Days in Lactation' },
  { property: 'ageInDays', label: 'Age in Days' },
  { property: 'startDateTime', label: 'Start Date Time' },
  { property: 'reportingDateTime', label: 'Reporting Date Time' },
  { property: 'alertType', label: 'Alert Type' },
  { property: 'duration', label: 'Duration' },
  { property: 'originalStartDateTime', label: 'Original Start Date Time' },
  { property: 'endDateTime', label: 'End Date Time' },
  { property: 'daysInPregnancy', label: 'Days in Pregnancy' },
  { property: 'newGroupId', label: 'New Group ID' },
  { property: 'newGroupName', label: 'New Group Name' },
  { property: 'currentGroupId', label: 'Current Group ID' },
  { property: 'currentGroupName', label: 'Current Group Name' },
  { property: 'destinationGroup', label: 'Destination Group' },
  { property: 'destinationGroupName', label: 'Destination Group Name' },
  { property: 'calvingEase', label: 'Calving Ease' },
  { property: 'oldLactationNumber', label: 'Old Lactation Number' },
  { property: 'newborns', label: 'Newborns' },
  { property: 'birthDateCalculated', label: 'Birth Date Calculated' },
  { property: 'sire', label: 'Sire' },
  { property: 'breedingNumber', label: 'Breeding Number' },
  { property: 'isOutOfBreedingWindow', label: 'Out of Breeding Window' },
  { property: 'interval', label: 'Interval' },
];
